# Generated by Django 5.1.4 on 2024-12-13 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.JSONField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Mixed-use", "Mixed-use"),
                        ],
                        max_length=50,
                    ),
                ),
                ("approved_docs", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OccupancyCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(upload_to="occupancy_certificates/"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissioningReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("Fire System", "Fire System"),
                            ("Electrical System", "Electrical System"),
                            ("Water Supply System", "Water Supply System"),
                            ("Drainage System", "Drainage System"),
                            ("Vertical Movement System", "Vertical Movement System"),
                            ("Ventilation System", "Ventilation System"),
                        ],
                        max_length=100,
                    ),
                ),
                ("rating", models.IntegerField()),
                ("report_file", models.FileField(upload_to="reports/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Architect", "Architect"),
                            ("Engineer", "Engineer"),
                            ("Contractor", "Contractor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("practicing_number", models.CharField(max_length=255, unique=True)),
                ("certificate", models.FileField(upload_to="certificates/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
