# Generated by Django 5.1.4 on 2024-12-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_approveddrawings_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="ready_for_approval",
            field=models.BooleanField(default=False),
        ),
    ]
