# Generated by Django 5.1.4 on 2024-12-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_approved_project_ready_for_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="overall",
            field=models.FileField(default=1, upload_to="reports/overall/"),
            preserve_default=False,
        ),
    ]
