# Generated by Django 5.1.4 on 2024-12-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_reports_overall"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="approved",
            new_name="approved_for_commissioning",
        ),
        migrations.AddField(
            model_name="project",
            name="approved_for_occupancy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commissioningreport",
            name="system",
            field=models.CharField(
                choices=[
                    ("Overall System", "Overall System"),
                    ("Fire System", "Fire System"),
                    ("Electrical System", "Electrical System"),
                    ("Water Supply System", "Water Supply System"),
                    ("Drainage System", "Drainage System"),
                    ("Vertical Movement System", "Vertical Movement System"),
                    ("Ventilation System", "Ventilation System"),
                ],
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Reports",
        ),
    ]
