# Generated by Django 5.1.4 on 2024-12-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_approved_project_approved_for_commissioning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approveddrawings",
            name="proposed_electricity",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/electricity/"
            ),
        ),
        migrations.AlterField(
            model_name="approveddrawings",
            name="proposed_sewer",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/sewer/"
            ),
        ),
        migrations.AlterField(
            model_name="approveddrawings",
            name="proposed_water",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/water/"
            ),
        ),
        migrations.AlterField(
            model_name="approveddrawings",
            name="structural",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/structural/"
            ),
        ),
    ]
