# Generated by Django 5.1.4 on 2024-12-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_approveddrawings_proposed_electricity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="architectural",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/architectural/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="proposed_electricity",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/electricity/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="proposed_sewer",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/sewer/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="proposed_water",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/water/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="structural",
            field=models.FileField(
                blank=True, null=True, upload_to="approved_drawings/structural/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="approved_docs",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
