# Generated by Django 5.1.4 on 2024-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_project_ready_for_commissioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ready_for_admin_review",
            field=models.BooleanField(default=False),
        ),
    ]
