# Generated by Django 5.1.4 on 2024-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholder",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="role",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner"),
                    ("Architect", "Architect"),
                    ("Engineer", "Engineer"),
                    ("Contractor", "Contractor"),
                ],
                max_length=50,
            ),
        ),
    ]
