# Generated by Django 5.1.4 on 2024-12-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_stakeholder_email_stakeholder_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": [
                    (
                        "can_toggle_ready_for_admin_review",
                        "Can toggle ready for admin review",
                    )
                ]
            },
        ),
    ]
